### ISSUE TITLE
What are we supposed to do if a solution have two solution? 

### ISSUE THREAD

**Issue by Vivekyadavgithub** [codewithvk/CP-List#3]
Say a question have a dp solution and a greedy solution what are we supposed to name file.

**Comment by codewithvk** [comment]
Then You can add file name such that people easily figure out ex(cppsol1.cpp,cppsol2.cpp)

**Comment by Vivekyadavgithub** [comment]
Wanna start a Dsa List as well??

**Comment by codewithvk** [comment]
@Vivekyadavgithub Dsa list which?? 
Love Babbar or Striver?

**Comment by Vivekyadavgithub** [comment]
Pepcoding but all have similar question so anything you want

**Comment by codewithvk** [comment]
No brother, It is only Striver Cp list.

You can surely create your own repo. I will surely contribute.

**Comment by Vivekyadavgithub** [comment]
ok
